Archive-31-12-2022/MyPages/articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path('', views.article_list, name="article_list"),
    path('detail/<int:pk>/', views.article_detail, name="article_detail"),
    path('create/', views.article_create, name="article_create"),
]

Archive-31-12-2022/MyPages/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # If you want to include url set in each app, write as:
    path("", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Archive-31-12-2022/MyPages/articles/models.py
from email.policy import default
from django.db import models
from django.utils import timezone
import uuid

class Article(models.Model):
    title = models.CharField('タイトル', max_length=100, default="untitled")  # 記事のタイトル
    thumbnail = models.ImageField(upload_to='uploads/%Y/%m/%d/', default="materials/NontalonLogo.png")  # 記事のサムネイル
    caption = models.CharField('Caption', max_length=120, default="")  # 記事のサムネイルのキャプション
    author = models.CharField(max_length=255, default="anonymous")  # 記事の作者
    description = models.TextField()  # 記事の概要
    body = models.TextField(default="")  # 記事の内容
    is_public = models.BooleanField('Public Article?', default=True)  # 記事の公開設定 Trueなら公開
    is_picked_up = models.BooleanField('Picked up Article?', default=False)  # 記事のPick Up設定 Trueならトップなどに公開される
    created_at = models.DateTimeField('Created at', default=timezone.now)  # 記事の作成日時 自動記録
    updated_at = models.DateTimeField('Updated at', default=timezone.now)  # 記事の追記日時 自動記録

    def __str__(self):
        return self.title

Archive-31-12-2022/MyPages/articles/forms.py
from django import forms
from .models import Article

class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ("title", "thumbnail", "caption", "author", "description", "body")
        labels = {
            "title": "TITLE",
            "thumbnail": "THUMBNAIL",
            "caption": "CAPTION",
            "author": "AUTHOR",
            "description": "DESCRIPTION",
            "body": "BODY"
        }
        help_texts = {
            "title": "TITLE",
            "thumbnail": "THUMBNAIL",
            "caption": "CAPTION",
            "author": "AUTHOR",
            "description": "DESCRIPTION",
            "body": "BODY"
        }

Archive-31-12-2022/MyPages/articles/views.py
from django.shortcuts import redirect, render
from django.urls import is_valid_path
from .forms import ArticleCreateForm

from .models import Article

def article_list(request):
    template_name = "articles/article_list.html"
    articles = Article.objects.all().order_by("-created_at")
    picked_up_articles = Article.objects.filter(is_picked_up=True).order_by("-created_at")

    content = {
        "articles": articles,
        "picked_up_articles": picked_up_articles,
    }
    return render(request, template_name, content)

def article_detail(request, pk):
    article = Article.objects.get(pk = pk)
    content = {
        "article": article,
        "twitter_card": article,
    }
    template_name = "articles/article_detail.html"
    return render(request, template_name, content)

def article_create(request):
    params = {"title": "", "thumbnail": "", "caption": "", "author": "", "description": "", "body": "", "from": None}

    if request.method == 'POST':
        form = ArticleCreateForm(request.POST)

        if form.is_valid():
            form.save()
        else:
            print("ret")
        # return redirect(article_list)
    else:
        params['form'] = ArticleCreateForm()

    content = {}
    template_name = "articles/article_create.html"
    return render(request, template_name, params)

Archive-31-12-2022/MyPages/articles/templates/articles/article_create.html
{% extends "global/extends/base.html" %}
{% load static %}

{% block main %}

<main class="main">

  <div class="doubleFrame">

    
    <div class="doubleFrame_main">
      
      <h1>記事の新規作成</h1>
        <form method="POST" novalidate>
            {% csrf_token %}

            <div class="generic-form">
              {{ form.title }}
            </div>

            <div>
              {{ form.thumbnail }}
            </div>

            <div class="generic-form">
              {{ form.caption }}
            </div>

            <div class="generic-form">
              {{ form.author }}
            </div>

            <div class="generic-form">
              {{ form.description }}
            </div>

            <div class="generic-form">
              {{ form.body }}
            </div>

            <button type="submit">送信</button>
        </form>
        <p>{{ message }}</p>

    </div>

    <div class="doubleFrame_nav --stick">

      <div class="headlineWithLeftLine">
        Getting Started
      </div>
      <ul class="colList">
        <li class="colListItem">INSTALLATION</li>
        <li class="colListItem">CREATE APP</li>
        <li class="colListItem">fjaklf</li>
        <li class="colListItem">fjaklf</li>
      </ul>

    </div>


  </div>

</main>

{% endblock %}

Archive-31-12-2022/MyPages/articles/templates/articles/article_detail.html
{% extends "global/extends/base.html" %}
{% load static %}

{% block main %}

<main class="main">

  <div class="doubleFrame">

    
    <div class="doubleFrame_main">
      
      <div class="pageTitle">
        {{ article.title }}
      </div>

      <div class="article">

        <div class="articleCreatedAt">
          {{ article.created_at|date:"nS F, Y" }}
        </div>

        <div class="articleBody">

          {{ article.body }}

        </div>

        <div class="itemWithIcon articleInfo">
          <div class="articleInfoAuthor">
            ISUUED BY {{ article.author }}
          </div>
          <img src="{% static 'media/generalLib.jpeg' %}" class="articleInfoAuthorIcon circleIcon">
        </div>

      </div>

      {% include "global/includes/footer_actions.html" %}

    </div>

    <div class="doubleFrame_nav --stick">

      <div class="headlineWithLeftLine">
        Getting Started
      </div>
      <ul class="colList">
        <li class="colListItem">INSTALLATION</li>
        <li class="colListItem">CREATE APP</li>
        <li class="colListItem">fjaklf</li>
        <li class="colListItem">fjaklf</li>
      </ul>

    </div>


  </div>

</main>

{% endblock %}

Archive-31-12-2022/MyPages/articles/templates/articles/article_list.html
{% extends "global/extends/base.html" %}
{% load static %}

{% block main %}

<main class="main">

  <div class="doubleFrame">

    <div class="doubleFrame_main">
      <ul class="articleList">

        {% for article in articles %}
        <li class="articleList_item">
  
          <div class="articleList_item_thumbnail">
            <img src="{{ article.thumbnail.url }}" alt="">
          </div>

          <div class="articleList_item_caption">
            {{ article.caption }}
          </div>
  
          <div class="articleList_item_title">
            <a class="hoverableLink" href="{% url 'articles:article_detail' article.pk %}">{{ article.title }}</a>
          </div>
  
          <div class="articleList_item_author">
            By {{ article.author }}
          </div>
  
          <div class="articleList_item_description">
            {{ article.description }}
          </div>
  
        </li>

        {% empty %}
        <div class="articleList_item_title">
          No Article was posted
        </div>
        {% endfor %}

        <a class="embeddedLink" href="{% url 'articles:article_create' %}">
          <div class="buttonHoveringChange">
            New Post
          </div>  
        </a>
        
      </ul>
    </div>

    <nav class="doubleFrame_nav">
      <ul class="articleList">
        <li class="articleList_item">

          <div class="articleList_item_pickUp">
            Live Article
          </div>
  
          <div class="articleList_item_title">
            Website design policy published
          </div>
  
          <div class="articleList_item_author">
            By okmtyuta
          </div>
  
          <div class="articleList_item_description">
            Website design policy published.
          </div>
  
        </li>
      </ul>
    </nav>

  </div>

</main>

{% endblock %}

Archive-31-12-2022/MyPages/templates/global/extends/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>Article | Nostalon</title>

    {% if description %}
      <meta name="description" content="{{ description }}">
    {% else %}
      <meta name="description" content="Free Web tutorials">
    {% endif %}


    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">

    <!-- styles -->
    <link rel="stylesheet" href="{% static 'css/entry.css' %}">

    <!-- scripts -->
    <script type="module" src="{% static 'js/entry.js' %}"></script>

    <!-- favicon -->
    <!-- <link rel="icon" href="{% static 'global/media/NontalonLogo.png' %}"> -->

    <!-- Google Font references -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nixie+One&family=UnifrakturMaguntia&display=swap" rel="stylesheet">  

    <!-- Material Icons -->
    <link rel="stylesheet" href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <!-- third party library -->
    <script src="https://kit.fontawesome.com/c226d01fbd.js" crossorigin="anonymous"></script>


    <!-- Twitter Card -->
    {% include "global/includes/twitter_card.html" %}
  </head>


  <body>
    
    <header class="header">
      
      <div class="header-logo">
        <div>
          <a class="noDecoratedLink" href="#">
            okmtyuta Engineering
          </a>
        </div>
      </div>

      <ul class="rowList--grid header-utils">
        <a class="underlineWhenHoverFromCenter embeddedLink" href="#">
          <li class="itemWithIcon header-menu-item">
            <span class="material-symbols-outlined">
              search
            </span>
            <div class="itemWithIconContent">
              Search
            </div>
          </li>
        </a>

        <a class="underlineWhenHoverFromCenter embeddedLink" href="{% url 'admin:index' %}">
          <li class="itemWithIcon header-menu-item">
            <span class="material-symbols-outlined">
              person
            </span>
            <div class="itemWithIconContent">
              Log In
            </div>
          </li>
        </a>
      </ul>

      <ul class="rowList--grid header-menu">
        <a class="underlineWhenHoverFromCenter embeddedLink" href="{% url 'articles:article_list' %}">
          <li class="itemWithIcon header-menu-item">
            <span class="material-symbols-outlined">
              article
            </span>
            <div class="itemWithIconContent">
              Articles
            </div>
          </li>
        </a>

        <a class="underlineWhenHoverFromCenter embeddedLink" href="#">
          <li class="itemWithIcon header-menu-item">
            <span class="material-symbols-outlined">
              gesture
            </span>
            <div class="itemWithIconContent">
              Illust
            </div>
          </li>
        </a>

        <a class="underlineWhenHoverFromCenter embeddedLink" href="#">
          <li class="itemWithIcon header-menu-item">
            <span class="material-symbols-outlined">
              code
            </span>
            <div class="itemWithIconContent">
              Dev
            </div>
          </li>
        </a>

        <!-- <a class="underlineWhenHoverFromCenter embeddedLink" href="#">
          <li class="itemWithIcon headerMenuItem">
            <span class="material-symbols-outlined">
              functions
            </span>
            <div class="itemWithIconContent">
              Math
            </div>
          </li>
        </a> -->

        <!-- <a class="underlineWhenHoverFromCenter embeddedLink" href="#">
          <li class="itemWithIcon headerMenuItem">
            <span class="material-symbols-outlined">
              photo
            </span>
            <div class="itemWithIconContent">
              Picture
            </div>
          </li>
        </a> -->

      </ul>

    </header>
    

    {% block main %}
    {% endblock %}


    <footer class="footer">


      <div class="band-50">
      </div>


      <div class="forDesktopAndTablet singleFrame">

        <ul class="rowList--flex --annotationCharSize">

          <li class="footerMenuSection">
            <div class="footerMenuCategory thirdHeadlineWithLeftLine">
              More Info
            </div>
            <ul class="footerMenuList colList">
              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="./coding_rules.html">
                  Coding Rules
                </a>
              </li>
              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="./styling_guide.html">
                  Styling Guidelines
                </a>
              </li>
              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="./nostalon_creation_exhibition.html">
                  Atelier
                </a>
              </li>
              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="./css_animation.html">
                  Anime
                </a>
              </li>
            </ul>
          </li>

          <li class="footerMenuSection">
            <div class="footerMenuCategory thirdHeadlineWithLeftLine">
              SNS
            </div>
            <ul class="footerMenuList rowList--flex">

              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="#"><i class="fa-brands fa-twitter fa-2x"></i></a>
              </li>
              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="#"><i class="fa-brands fa-youtube fa-2x"></i></a>
              </li>
              
            </ul>
          </li>

        </ul>

      </div>


      <ul class="forMobile">

        <li>
          <a class="bandLink" href="#">
            <div class="bandLinkContent">
              To be prepared
            </div>
          </a>
        </li>

        <li>
          <a class="bandLink" href="#">
            <div class="bandLinkContent">
              To be prepared
            </div>
          </a>
        </li>

      </ul>


      <div class="footerCopyRight">
        2020 - 2022 © Nostalon
      </div>

    </footer>


  </body>
</html>

Archive-31-12-2022/MyPages/templates/global/includes/footer_actions.html
<div class="newspaper_footer">
          
  <div class="newspaper_footer_action">
    <div class="comments itemWithIcon newspaper_footer_action_item">
      <span class="material-symbols-outlined">
        comment
      </span>

        Comments
    </div>

    <div class="shares itemWithIcon newspaper_footer_action_item">
      <span class="material-symbols-outlined">
        ios_share
      </span>

      Share

    </div>

    <div class="itemWithIcon copyUrl newspaper_footer_action_item">
      <span class="material-symbols-outlined">
        link
      </span>

      Link
      <div class="copiedAlert">
        Copied
      </div>
    </div>
  </div>

</div>

Archive-31-12-2022/MyPages/templates/global/includes/google_custom_search.html
<script async src="https://cse.google.com/cse.js?cx=993e34edc2f5ffad5"></script>
<div class="gcse-search"></div>

Archive-31-12-2022/MyPages/templates/global/includes/twitter_card.html
{% load static %}

{% if twitter_card %}
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@nostalon_JP" />
  <meta name="twitter:domain" content="okmtyuta.nostalon.jp" />
  <meta name="twitter:title" content="{{ twitter_card.title }}" />
  <meta name="twitter:description" content="{{ twitter_card.description }}" />
  <meta name="twitter:image" content="{{ twitter_card.thumbnail.url }}" />
{% else %}
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@nostalon_JP" />
  <meta name="twitter:domain" content="okmtyuta.nostalon.jp" />
  <meta name="twitter:title" content="Nostalon" />
  <meta name="twitter:description" content="Nostalon New News Network" />
  <meta name="twitter:image" content="" />
{% endif %}