Archive-31-12-2022/nostalon/articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path('', views.article_list, name="article_list"),
    path('detail/<int:pk>/', views.article_detail, name="article_detail"),
]

Archive-31-12-2022/nostalon/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # If you want to include url set in each app, write as:
    path("", include("pages.urls")),
    path("newspapers/", include("newspapers.urls")),
    path("articles/", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Archive-31-12-2022/nostalon/newspapers/urls.py
from django.urls import path

from . import views

app_name = "newspapers"

urlpatterns = [
    path('', views.newspaper_list, name="newspaper_list"),
    path('detail/<int:pk>/', views.newspaper_detail, name="newspaper_detail"),
]

Archive-31-12-2022/nostalon/pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path('', views.nostalon_top, name="nostalon_top"),
    path('coming_soon', views.coming_soon, name="coming_soon"),
    path('users/detail', views.user_detail, name="user_detail"),
    path('guidelines/global_design', views.GlobalDesignGuidelineView.as_view(), name="global_design_guideline"),
    path('variable', views.variable, name="variable"),
]

Archive-31-12-2022/nostalon/articles/models.py
from email.policy import default
from django.db import models
from django.utils import timezone

class Article(models.Model):
    title = models.CharField('タイトル', max_length=100)
    thumbnail = models.ImageField(upload_to='uploads/%Y/%m/%d/', default="materials/NontalonLogo.png")
    caption = models.CharField('Caption', max_length=120, default="")
    author = models.CharField(max_length=255)
    description = models.TextField()
    body = models.TextField()
    is_public = models.BooleanField('Public Article?', default=True)
    is_picked_up = models.BooleanField('Picked up Article?', default=False)
    created_at = models.DateTimeField('Created at', default=timezone.now)
    updated_at = models.DateTimeField('Updated at', default=timezone.now)

    def __str__(self):
        return self.title

Archive-31-12-2022/nostalon/newspapers/models.py
from django.db import models
from django.utils import timezone

class Newspaper(models.Model):
    title = models.CharField('タイトル', max_length=100)
    thumbnail = models.ImageField(upload_to='uploads/%Y/%m/%d/', default="materials/NontalonLogo.png")
    caption = models.CharField('Caption', max_length=120, default="")
    author = models.CharField(max_length=255)
    description = models.TextField()
    body = models.TextField()
    is_public = models.BooleanField('Public Article?', default=True)
    is_picked_up = models.BooleanField('Picked up Article?', default=False)
    created_at = models.DateTimeField('Created at', default=timezone.now)
    updated_at = models.DateTimeField('Updated at', default=timezone.now)

    def __str__(self):
        return self.title

Archive-31-12-2022/nostalon/pages/models.py
from django.db import models
from django.utils import timezone

class UpdateInfo(models.Model):
    title = models.CharField('Title', max_length=100)
    description = models.TextField()
    body = models.TextField()
    is_public = models.BooleanField('Public Article?', default=True)
    created_at = models.DateTimeField('Created at', default=timezone.now)
    updated_at = models.DateTimeField('Updated at', default=timezone.now)

    def __str__(self):
        return self.title

Archive-31-12-2022/nostalon/articles/views.py
from django.shortcuts import render
from .models import Article

def article_list(request):
    template_name = "articles/article_list.html"
    articles = Article.objects.all().order_by("-created_at")
    picked_up_articles = Article.objects.filter(is_picked_up=True).order_by("-created_at")

    context = {
        "articles": articles,
        "picked_up_articles": picked_up_articles,
    }
    return render(request, template_name, context)

def article_detail(request, pk):
    article = Article.objects.get(pk = pk)
    context = {
        "article": article,
        "twitter_card": article,
    }
    template_name = "articles/article_detail.html"
    return render(request, template_name, context)

Archive-31-12-2022/nostalon/newspapers/views.py
from django.shortcuts import render
from .models import Newspaper

def newspaper_list(request):
    template_name = "newspapers/newspaper_list.html"
    newspapers = Newspaper.objects.all().order_by("-created_at")
    picked_up_newspapers = Newspaper.objects.filter(is_picked_up=True).order_by("-created_at")

    context = {
        "newspapers": newspapers,
        "picked_up_newspapers": picked_up_newspapers,
    }
    return render(request, template_name, context)

def newspaper_detail(request, pk):
    newspaper = Newspaper.objects.get(pk = pk)
    context = {
        "newspaper": newspaper,
        "twitter_card": newspaper,
    }
    template_name = "newspapers/newspaper_detail.html"
    return render(request, template_name, context)

Archive-31-12-2022/nostalon/pages/views.py
from re import template
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import UpdateInfo

# Create your views here.
def nostalon_top(request):
    template_name = "pages/nostalon_top.html"
    update_infos = UpdateInfo.objects.all().order_by("-created_at")
    context = {
        "update_infos": update_infos
    }
    return render(request, template_name, context)


def coming_soon(request):
    template_name = "pages/coming_soon.html"
    return render(request, template_name)

def user_detail(request):
    template_name = "pages/user_detail.html"
    return render(request, template_name)

class GlobalDesignGuidelineView(TemplateView):
    template_name = "pages/global_design_guideline.html"

def variable(request):
    template_name = "pages/variable.html"
    return render(request, template_name)

Archive-31-12-2022/nostalon/articles/templates/articles/article_detail.html
{% extends "global/extends/base.html" %}
{% load static %}

{% block main %}

<main class="main">

  <div class="doubleFrame">

    
    <div class="doubleFrame_main">
      
      <div class="pageTitle">
        {{ article.title }}
      </div>

      <div class="article">

        <div class="articleCreatedAt">
          {{ article.created_at|date:"nS F, Y" }}
        </div>

        <div class="articleBody">

          {{ article.body }}Djangoではテンプレート上で表示させる日付のフォーマットを任意で変更することが可能です。表示の変更方法はテンプレートの組み込みフィルタ「date」を利用し、引数に書式を指定することで設定します。

          引数での書式設定に使えるフォーマット文字列は下記の一覧表ご参照ください。
          
          
          
        </div>

        <div class="itemWithIcon articleInfo">
          <div class="articleInfoAuthor">
            ISUUED BY {{ article.author }}
          </div>
          <img src="{% static 'pages/media/generalLib.jpeg' %}" class="articleInfoAuthorIcon circleIcon">
        </div>

      </div>

      {% include "global/includes/footer_actions.html" %}

    </div>

    <div class="doubleFrame_nav --stick">

      <div class="headlineWithLeftLine">
        Getting Started
      </div>
      <ul class="colList">
        <li class="colListItem">INSTALLATION</li>
        <li class="colListItem">CREATE APP</li>
        <li class="colListItem">fjaklf</li>
        <li class="colListItem">fjaklf</li>
      </ul>

    </div>


  </div>

</main>

{% endblock %}

Archive-31-12-2022/nostalon/articles/templates/articles/article_list.html
{% extends "global/extends/base.html" %}
{% load static %}

{% block main %}

<main class="main">

  <div class="doubleFrame">

    <div class="doubleFrame_main">
      <ul class="articleList">

        {% for article in articles %}
        <li class="articleList_item">
  
          <div class="articleList_item_thumbnail">
            <img src="{{ article.thumbnail.url }}" alt="">
          </div>

          <div class="articleList_item_caption">
            {{ article.caption }}
          </div>
  
          <div class="articleList_item_title">
            <a class="hoverableLink" href="{% url 'articles:article_detail' article.pk %}">{{ article.title }}</a>
          </div>
  
          <div class="articleList_item_author">
            By {{ article.author }}
          </div>
  
          <div class="articleList_item_description">
            {{ article.description }}
          </div>
  
        </li>

        {% empty %}
        <div class="articleList_item_title">
          No Article was posted
        </div>
        {% endfor %}

      </ul>
    </div>

    <nav class="doubleFrame_nav">
      <ul class="articleList">
        <li class="articleList_item">

          <div class="articleList_item_pickUp">
            Live Article
          </div>
  
          <div class="articleList_item_title">
            Website design policy published
          </div>
  
          <div class="articleList_item_author">
            By okmtyuta
          </div>
  
          <div class="articleList_item_description">
            Website design policy published.
          </div>
  
        </li>
      </ul>
    </nav>

  </div>

</main>

{% endblock %}

Archive-31-12-2022/nostalon/newspapers/templates/newspapers/newspaper_detail.html
{% extends "global/extends/base.html" %}
{% load static %}

{% block main %}

  <main class="main">

    <div class="singleFrame">

      <div class="newspaper">

        <div class="newspaper_title">
          {{ newspaper.title }}
        </div>

        <div class="newspaper_author">
          By {{ newspaper.author }}
        </div>

        <div class="newspaper_postedAt">
          Posted at {{ newspaper.created_at|date:"nS F, Y" }}
        </div>

        <div class="newspaper_body">
          {% autoescape off %}
            {{ newspaper.body }}
          {% endautoescape %}

        </div>

        {% include "global/includes/footer_actions.html" %}


        <!-- <div class="paper updateLogs">
          <div class="paper_headline">
            HEADLINE
          </div>
  
          <ul class="itemization">
  
            <li class="itemization_item">
              <div class="itemization_item_heading">
                TODAY
              </div>
              created...
            </li>
            <li class="itemization_item">
              <div class="itemization_item_heading">
                TODAY
              </div>
              created...
            </li>
            <li class="itemization_item">
              <div class="itemization_item_heading">
                TODAY
              </div>
              created...
            </li>
            <li class="itemization_item">
              <div class="itemization_item_heading">
                TODAY
              </div>
              created...
            </li>
            <li class="itemization_item">
              <div class="itemization_item_heading">
                TODAY
              </div>
              created...
            </li>
  
          </ul>
        </div> -->

      </div>
      
    </div>

  </main>

{% endblock %}

Archive-31-12-2022/nostalon/newspapers/templates/newspapers/newspaper_list.html
{% extends "global/extends/base.html" %}
{% load static %}

{% block main %}

<main class="main">

  <div class="tripleFrame">

    <aside class="tripleFrame_aside">
      <div class="topicNews">
        <ul class="newspaperList">
          {% for picked_up_newspaper in picked_up_newspapers %}
          <li class="newspaperList_item">
    
            <div class="newspaperList_item_title">
              <a class="hoverableLink" href="{% url 'pages:article_detail' picked_up_article.pk %}">{{ picked_up_newspaper.title }}</a>
            </div>
    
            <div class="newspaperList_item_author">
              By {{ picked_up_newspaper.author }}
            </div>
    
            <div class="newspaperList_item_description">
              {{ picked_up_newspaper.description }}
            </div>
    
          </li>

          {% empty %}
          
            <div class="newspaperList_item_title">
              No Article was picked up
            </div>

          {% endfor %}
        
        </ul>
      </div>
    </aside>

    <div class="tripleFrame_main">
      <ul class="newspaperList">

        {% for newspaper in newspapers %}
        <li class="newspaperList_item">
  
          <div class="newspaperList_item_thumbnail">
            <img src="{{ newspaper.thumbnail.url }}" alt="">
          </div>

          <div class="newspaperList_item_caption">
            {{ newspaper.caption }}
          </div>
  
          <div class="newspaperList_item_title">
            <a class="hoverableLink" href="{% url 'newspapers:newspaper_detail' newspaper.pk %}">{{ newspaper.title }}</a>
          </div>
  
          <div class="newspaperList_item_author">
            By {{ newspaper.author }}
          </div>
  
          <div class="newspaperList_item_description">
            {{ newspaper.description }}
          </div>
  
        </li>

        {% empty %}
        <div class="newspaperList_item_title">
          No Article was posted
        </div>
        {% endfor %}

      </ul>
    </div>

    <nav class="tripleFrame_nav">
      <ul class="newspaperList">
        <li class="newspaperList_item">

          <div class="newspaperList_item_pickUp">
            Live Article
          </div>
  
          <div class="newspaperList_item_title">
            Website design policy published
          </div>
  
          <div class="newspaperList_item_author">
            By okmtyuta
          </div>
  
          <div class="newspaperList_item_description">
            Website design policy published.
          </div>
  
        </li>
      </ul>
    </nav>

  </div>

</main>

{% endblock %}